version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cervical-cancer-analysis-main
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_jupyter.sh
      timeout: 300
      runas: ec2-user
