version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cervical-cancer-analysis
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
